predict:
    test_ds: 
        "../testing_data/testing_sequence.fasta"
    weights: "../virhunter_data/models" # path to the folder containing weights for NN and RF modules trained on 500 and 1000 fragment lengths
    out_path: "../virhunter_data/output" # path to the folder to store predictions
    n_cpus: 2 # number of cpus you want to use
    return_viral: True # (True/False) True if you want to recuperate contigs annotated as viral
    limit: 750 # Do predictions only for contigs > l. We suggest default l=750, as it was tested in the paper
